
name: 'PR Required Tasks'
description: 'Require tasks to be completed in a PR.'
author: 'meagerfindings'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: check-square
  color: orange
